_core:
  default_config_hash: ijfbzDTN4CbE7Sr-6ubWzy_t1vH4OtU1doNCLssVz-4
langcode: en
uuid: b61b0763-01ad-4a5c-97b3-c91dd4cf5bda
name: 'MY NEWS24'
mail: swarnav.das@innoraft.com
slogan: ''
page:
  403: /node/2
  404: /node/3
  front: /node/1
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: ''
